# Generated by Django 5.2.4 on 2025-07-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="摄像头名称", max_length=100, unique=True),
                ),
                (
                    "rtsp_url",
                    models.CharField(help_text="摄像头的RTSP或视频流地址", max_length=512),
                ),
                (
                    "location_desc",
                    models.CharField(
                        blank=True, help_text="具体位置描述", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "摄像头",
                "verbose_name_plural": "摄像头",
            },
        ),
        migrations.CreateModel(
            name="DangerousArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="危险区域名称", max_length=100)),
                ("coordinates", models.JSONField(help_text="存储前端绘制的多边形顶点坐标数组")),
                (
                    "camera",
                    models.ForeignKey(
                        help_text="关联的摄像头",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dangerous_areas",
                        to="camera_management.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "危险区域",
                "verbose_name_plural": "危险区域",
            },
        ),
    ]
