# Generated by Django 5.2.4 on 2025-07-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="摄像头名称"),
                ),
                (
                    "rtsp_url",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="RTSP流地址"
                    ),
                ),
                (
                    "location_desc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="位置描述"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "摄像头",
                "verbose_name_plural": "摄像头管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DangerousArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="区域名称")),
                ("coordinates", models.JSONField(verbose_name="区域坐标 (JSON)")),
                (
                    "min_distance_threshold",
                    models.FloatField(
                        default=0.0,
                        help_text="人员距离边缘小于此值时告警",
                        verbose_name="距离边缘最小距离阈值(米)",
                    ),
                ),
                (
                    "time_in_area_threshold",
                    models.IntegerField(
                        default=0,
                        help_text="人员在区域内停留超过此值时告警",
                        verbose_name="区域内停留时间阈值(秒)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dangerous_areas",
                        to="camera_management.camera",
                        verbose_name="关联摄像头",
                    ),
                ),
            ],
            options={
                "verbose_name": "危险区域",
                "verbose_name_plural": "危险区域管理",
                "ordering": ["camera", "name"],
                "unique_together": {("camera", "name")},
            },
        ),
    ]
