# Generated by Django 5.2.4 on 2025-07-18 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "face_image",
                    models.ImageField(
                        upload_to="registered_faces/", verbose_name="人脸图像"
                    ),
                ),
                ("face_encoding", models.TextField(verbose_name="人脸编码数据")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("visitor", "访客"),
                            ("vip", "VIP"),
                            ("staff", "工作人员"),
                            ("other", "其他"),
                        ],
                        default="visitor",
                        max_length=50,
                        verbose_name="类别",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "注册人脸",
                "verbose_name_plural": "注册人脸",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_image",
                    models.ImageField(upload_to="faces/", verbose_name="人脸图像"),
                ),
                ("face_encoding", models.TextField(verbose_name="人脸编码数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_data",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "人脸数据",
                "verbose_name_plural": "人脸数据",
                "ordering": ["-created_at"],
            },
        ),
    ]
