# Generated by Django 5.2.4 on 2025-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_id", models.CharField(help_text="摄像头ID", max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        help_text="告警类型，如 'stranger_intrusion', 'person_fall'",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="告警发生时间"),
                ),
                (
                    "location",
                    models.JSONField(blank=True, help_text="存储坐标信息", null=True),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, help_text="算法置信度", null=True),
                ),
                (
                    "image_snapshot_url",
                    models.URLField(
                        blank=True, help_text="告警截图URL", max_length=512, null=True
                    ),
                ),
                (
                    "video_clip_url",
                    models.URLField(
                        blank=True, help_text="视频片段URL", max_length=512, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="告警状态，如 'pending', 'in_progress', 'resolved'",
                        max_length=20,
                    ),
                ),
                (
                    "handler",
                    models.CharField(
                        blank=True, help_text="处理人", max_length=100, null=True
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(blank=True, help_text="处理备注", null=True),
                ),
            ],
            options={
                "verbose_name": "告警事件",
                "verbose_name_plural": "告警事件",
                "ordering": ["-timestamp"],
            },
        ),
    ]
