# Generated by Django 5.2.4 on 2025-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("stranger_intrusion", "陌生人入侵"),
                            ("person_fall", "人员跌倒"),
                            ("fire_smoke", "明火烟雾"),
                            ("stranger_face_detected", "陌生人脸检测"),
                            ("spoofing_attack", "活体欺骗攻击"),
                            ("abnormal_sound_scream", "异常声音: 尖叫"),
                            ("abnormal_sound_fight", "异常声音: 打架"),
                            ("abnormal_sound_glass_break", "异常声音: 玻璃破碎"),
                            ("other", "其他异常"),
                        ],
                        max_length=50,
                        verbose_name="告警类型",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="告警时间")),
                ("location", models.JSONField(verbose_name="告警位置信息")),
                ("confidence", models.FloatField(verbose_name="置信度")),
                (
                    "image_snapshot_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="告警截图URL"
                    ),
                ),
                (
                    "video_clip_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="告警视频片段URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "处理中"),
                            ("resolved", "已解决"),
                            ("ignored", "已忽略"),
                        ],
                        max_length=20,
                        verbose_name="告警状态",
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(blank=True, null=True, verbose_name="处理备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "告警",
                "verbose_name_plural": "告警管理",
                "db_table": "alerts_alert",
                "ordering": ["-timestamp"],
                "managed": False,
            },
        ),
    ]
