# Generated by Django 5.2.4 on 2025-07-09 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "managed": False,
                "ordering": ["-timestamp"],
                "verbose_name": "告警",
                "verbose_name_plural": "告警管理",
            },
        ),
    ]
