# Generated by Django 4.2.16 on 2025-07-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'managed': True, 'ordering': ['-timestamp'], 'verbose_name': '告警', 'verbose_name_plural': '告警管理'},
        ),
    ]
